name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Vérifier la présence de index.html
        run: |
          if [ -f "./todo-app/src/frontend/index.html" ]; then
            echo "Le fichier index.html existe"
          else
            echo "Erreur : index.html n’existe pas !"
            exit 1
          fi

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_COAST_030DB1A10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./todo-app/src/frontend"
          api_location: ""
          output_location: "."

      - name: Lighthouse CI Action
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://todo.theopasquier.emf-informatique.ch/
          uploadArtifacts: false
          temporaryPublicStorage: true
          configPath: lighthouserc.json

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_COAST_030DB1A10 }}
          action: "close"
