name: Azure Static Web Apps CI/CD with Jira, Docker, and Kubernetes

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build, Verify Index, Push Docker Image, and Deploy to Kubernetes
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Étape de vérification de la présence de index.html
      - name: Vérifier la présence de index.html
        run: |
          if [ -f "./todo-app/src/frontend/index.html" ]; then
            echo "Le fichier index.html existe";
          else
            echo "Erreur : index.html n’existe pas !";
            exit 1;
          fi

      # Integration with Jira for automatic issue tracking via commits
      - name: Jira Integration
        run: |
          echo "Linking commits to Jira..."
          git log -1 --pretty=%B | grep -Eo '[A-Z]+-[0-9]+' | xargs -I {{}} echo "Jira Issue: {{}}"

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t myapp:${{ github.sha }} ./todo-app/src/frontend

      # Push Docker Image to ACR (Azure Container Registry) or Docker Hub
      - name: Push Docker Image to ACR
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login myregistry.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
          docker tag myapp:${{ github.sha }} myregistry.azurecr.io/myapp:${{ github.sha }}
          docker push myregistry.azurecr.io/myapp:${{ github.sha }}

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/myapp myapp=myregistry.azurecr.io/myapp:${{ github.sha }} --namespace=my-namespace

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_COAST_030DB1A10 }}
          action: "close"
