name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Vérifier la présence de index.html
        run: |
          if [ -f "./todo-app/src/frontend/index.html" ]; then
            echo "Le fichier index.html existe"
          else
            echo "Erreur : index.html n’existe pas!"
            exit 1
          fi
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_COAST_030DB1A10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./todo-app/src/frontend" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "." # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
      - name: Lighthouse CI Action
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://todo.theopasquier.emf-informatique.ch/
          temporaryPublicStorage: true

      - name: Vérifier le score d'accessibilité avec assertions
        run: |
          ACCESSIBILITY_SCORE=$(cat ./lighthouseci/report.json | jq '.categories.accessibility.score * 100')
          echo "Score d'accessibilité : $ACCESSIBILITY_SCORE"
          if (( $(echo "$ACCESSIBILITY_SCORE < 90" | bc -l) )); then
            echo "Erreur : Le score d'accessibilité est trop bas !"
            exit 1
          fi
        env:
          CI: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_COAST_030DB1A10 }}
          action: "close"
