name: Build and deploy container app to Azure Web App - WA-300621-Pasquier-Theo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://acr300621210.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_0f53828a369b468dbec20341bc172d76 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_07913f558c1442bdb33e38f8a46f9cba }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: acr300621210.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0f53828a369b468dbec20341bc172d76 }}/todo-app:${{ github.sha }}
        context: ./todo-app  # Changer le contexte ici pour le répertoire todo-app
        file: ./todo-app/src/backend/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'WA-300621-Pasquier-Theo'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_bb57dc47f92d493cb583b513df714dff }}
        images: 'acr300621210.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0f53828a369b468dbec20341bc172d76 }}/todo-app:${{ github.sha }}'
